### ISSUE TITLE
What's the use case?

### ISSUE THREAD

**Issue by FoxxMD** [Ardakilic/woodpecker-keyboard#1]
The entire setup is beautiful! Love those keycap colros and font, and the case is gorgeous.

I understand the split can be more ergonomic as wrists are further apart. What does the ortholinear layout contribute? And how are you using the middle space?

**Comment by Ardakilic** [comment]
The middle space is there not to bent your wrists a lot. It's like unibody split keyboard, and feels better. I can say this as a old planck keyboard user.

Ortholinear layout contributes a lot, you can watch Planck keyboard's introduction video here, it adverties ortholinear more than the product itself 😊  https://www.youtube.com/watch?v=bEPg8kk84gw

In the futue, I'm planning to utilize a trackpad there, but the driver for ZMK firmware did not merge it yet, so I'm waiting patiently.
